PLUGIN_NAME=		speedtest-statistics
PLUGIN_VERSION=		01
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		An application that start speedtest
PLUGIN_MAINTAINER=	clantoservices@gmail.com
.include "../../Mk/plugins.mk"
